"""Initial tables with map settings

Revision ID: 7a346d3f3bc6
Revises: 2c41b6cbb9f3
Create Date: 2025-06-19 12:02:24.885644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a346d3f3bc6'
down_revision: Union[str, None] = '2c41b6cbb9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nsw_land_zones_geom_idx', table_name='nsw_land_zones', postgresql_using='gist')
    op.drop_table('nsw_land_zones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nsw_land_zones',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('epi_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('lga_code', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lga_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('published_', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('commenced_', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('currency_d', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('amendment', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('map_type', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('map_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lay_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lay_class', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('sym_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('legis_ref_', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('legis_ref1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('legis_re_1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_us', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('created_da', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_edite', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('last_edi_1', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pco_ref_ke', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('epi_type', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('cadid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shape_leng', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('shape_area', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='nsw_land_zones_pkey')
    )
    op.create_index('nsw_land_zones_geom_idx', 'nsw_land_zones', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
