"""Add user_id to spatial tables

Revision ID: 9fe772951314
Revises: add_schema_permissions
Create Date: 2025-06-20 18:43:38.213015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe772951314'
down_revision: Union[str, None] = 'c4d2e7f83b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nsw_land_zones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nsw_land_zones',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('epi_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('lga_code', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lga_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('published_', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('commenced_', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('currency_d', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('amendment', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('map_type', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('map_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lay_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lay_class', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('sym_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('legis_ref_', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('legis_ref1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('legis_re_1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_us', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('created_da', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_edite', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('last_edi_1', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pco_ref_ke', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('epi_type', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('cadid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shape_leng', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('shape_area', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_nsw_land_zones_user')
    )
    # ### end Alembic commands ###
