"""Initial schema with all user and map fields

Revision ID: e187b5c1a137
Revises: 459a99e30e9c
Create Date: 2025-06-19 12:38:48.188026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e187b5c1a137'
down_revision: Union[str, None] = '459a99e30e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
